language: ruby

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -q build-essential freetds-dev libc6-dev

matrix:
  allow_failures:
    - rvm: jruby-9.1.9.0

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-9.1.9.0
