language: ruby

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-20mode
    - rvm: rbx-2
  fast_finish: true

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - jruby-19mode
  - jruby-20mode
  - rbx-2
