require 'purview/exceptions/base'
require 'purview/exceptions/table'
require 'purview/exceptions/could_not_acquire_lock'
require 'purview/exceptions/lock_already_released'
require 'purview/exceptions/no_table'
require 'purview/exceptions/no_window'
require 'purview/exceptions/rows_outside_window'
