require 'purview/exceptions/base'
require 'purview/exceptions/base_table'

require 'purview/exceptions/could_not_baseline_table'
require 'purview/exceptions/could_not_disable_table'
require 'purview/exceptions/could_not_enable_table'
require 'purview/exceptions/could_not_find_metadata_for_table'
require 'purview/exceptions/could_not_initialize_table'
require 'purview/exceptions/could_not_lock_table'
require 'purview/exceptions/could_not_sync_table'
require 'purview/exceptions/could_not_unlock_table'
require 'purview/exceptions/could_not_update_metadata_for_table'

require 'purview/exceptions/database_already_assigned_for_table'
require 'purview/exceptions/no_table'
require 'purview/exceptions/no_window_for_table'
require 'purview/exceptions/rows_outside_window_for_table'
require 'purview/exceptions/table_already_assigned_for_column'
require 'purview/exceptions/table_already_assigned_for_index'
require 'purview/exceptions/wrong_database_for_table'
