require 'purview/exceptions/base'
require 'purview/exceptions/base_table'

require 'purview/exceptions/could_not_baseline'
require 'purview/exceptions/could_not_disable'
require 'purview/exceptions/could_not_enable'
require 'purview/exceptions/could_not_find_table_metadata'
require 'purview/exceptions/could_not_initialize'
require 'purview/exceptions/could_not_lock'
require 'purview/exceptions/could_not_sync'
require 'purview/exceptions/could_not_unlock'

require 'purview/exceptions/database_already_assigned'
require 'purview/exceptions/no_table'
require 'purview/exceptions/no_window'
require 'purview/exceptions/rows_outside_window'
require 'purview/exceptions/table_already_assigned'
require 'purview/exceptions/wrong_database'
